import { StyleSheet } from "react-native";

export const dashboardStyles = StyleSheet.create({
    container: {
    padding: 16,
    paddingBottom: 100,
    backgroundColor: "#FDF7F1",
    },
  totalIncomeCard: {
    backgroundColor: "#FDF7F1",
    borderRadius: 10,
    marginBottom: 12,
    elevation: 2,
  },
  cardLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#5A5856",
  },
  totalIncomeText: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#6F32AB",
    marginTop: 8,
  },
  withdrawBtn: {
    backgroundColor: "#6F32AB",
    borderRadius: 10,
    marginBottom: 20,
  },
  rowGap: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  infoCard: {
    flex: 1,
    padding: 12,
    borderRadius: 12,
  },
  greenCard: {
    backgroundColor: "#FDF7F1",
    marginRight: 8,
    elevation: 0,
    shadowOpacity: 0,
  },
  redCard: {
    backgroundColor: "#FDF7F1",
    marginLeft: 8,
    elevation: 0,
    shadowOpacity: 0,
  },
  infoLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: "#1AB760",
    marginLeft: 0,
  },
  expenseLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: "#E43D3D",
    marginLeft: 0,
  },
  infoAmount: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#5A5856",
    marginVertical: 4,
  },
  trendRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
    justifyContent: "flex-start",
  },
  trendCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 6,
  },
  trendIcon: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  trendText: {
    fontSize: 14,
    fontWeight: "500",
  },
  iconRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
    justifyContent: "flex-start",
  },
  orderCard: {
    paddingBottom: 16,
    borderRadius: 12,
    backgroundColor: "#FDF7F1",
    marginTop: 10,
  },
  yearDropdown: {
    backgroundColor: "#FDF7F1",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 16,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    minWidth: 80,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  yearText: {
    fontSize: 13,
    color: "#5A5856",
    fontWeight: "500",
    marginRight: 4,
  },
  orderRow: {
    marginBottom: 16,
  },
  orderMainCard: {
    borderRadius: 12,
    backgroundColor: "#FDF7F1",
    elevation: 2,
    paddingVertical: 6,
  },
  orderImage: {
    width: 50,
    height: 50,
    marginRight: 12,
    resizeMode: "contain",
  },
  totalOrderLabel: {
    fontSize: 12,
    color: "#999",
  },
  totalOrderValue: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#5A5856",
  },
  orderSmallCard: {
    flex: 1,
    marginHorizontal: 4,
    backgroundColor: "#FDF7F1",
    borderRadius: 10,
    elevation: 0,
    shadowOpacity: 0,
  },
  smallCardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  smallCardLabel: {
    fontSize: 12,
    color: "#A9A9A9",
    marginLeft: 8,
  },
  smallCardValue: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#5A5856",
  },
  progressContainer: {
    marginTop: 16,
    marginBottom:16,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  targetText: {
    fontSize: 14,
    color: "#555",
  },
  progressTrack: {
    height: 10,
    borderRadius: 6,
    backgroundColor: "#FDF7F1",
    width: "100%",
  },
  progressFill: {
    height: 10,
    borderRadius: 6,
    backgroundColor: "#FA4A0C",
  },
  progressValue: {
    fontSize: 14,
    color: "#888",
  },
  statusGrid: {
  flexDirection: "row",
  flexWrap: "wrap",
  justifyContent: "space-between",
  marginTop: 12,
},
statusItem: {
  width: "47%",
  marginBottom: 20,
  backgroundColor: "#FDF7F1",
  borderRadius: 12,
  padding: 12,
  alignItems: "flex-start",
  elevation: 2,
},
statusIcon: {
  width: 40,
  height: 40,
  resizeMode: "contain",
  marginBottom: 8,
},
statusLabel: {
  textAlign: "left",
  fontSize: 12,
  color: "#777",
  marginBottom: 4,
},
  statusValue: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#5A5856",
  },
  legendContainer: {
    width: "100%",
    marginTop: 16,
  },
  legendTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#5A5856",
    marginBottom: 12,
    textAlign: "left",
  },
legendItem: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  marginBottom: 8,
  paddingHorizontal: 12,
},
legendDot: {
  width: 12,
  height: 12,
  borderRadius: 3,
  marginRight: 8,
},
legendLabel: {
  flex: 1,
  fontSize: 13,
  color: "#666",
},
  legendValue: {
    fontSize: 13,
    fontWeight: "600",
    color: "#5A5856",
  },
  menuItem: {
    backgroundColor: "#FDF7F1",
    borderRadius: 6,
    marginHorizontal: 4,
    marginVertical: 2,
  },
  menuItemText: {
    color: "#5A5856",
    fontSize: 13,
    fontWeight: "500",
  },
  orangeCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#FA4A0C",
    backgroundColor: "#FDF7F1",
    justifyContent: "center",
    alignItems: "center",
  },
  orangeCircleInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#FDF7F1",
  },

});
